tap "dapr/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"

# build tools
brew "automake"
brew "autoconf"
brew "autoconf-archive"
brew "pkg-config"
brew "gnumake"
brew "cmake"
brew "libtool"
brew "net-tools"

# utils
brew "bat"
brew "zsh"
brew "jq"
brew "yq"
brew "tree"
brew "htop"
brew "fzf"
brew "watch"
brew "ripgrep"
brew "the_silver_searcher"
brew "git"
brew "gnupg"
brew "coreutils"
brew "gh"

# internet
brew "youtube-dl"
brew "wget"
brew "axel"
brew "curl"

# programming/sdks
brew "python3"
brew "ruby"
brew "go"
brew "node"
brew "yarn"
brew "openjdk"
brew "rustup"
brew "dotnet-sdk"

# container/devops"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "docker-credential-helper-ecr"
brew "kubectl"
brew "kubectx"
brew "helm"
brew "kind"
brew "terraform"
brew "pulumi"
brew "vault"
brew "google-cloud-sdk"
brew "packer"

# virtualization
cask "vagrant"
brew "qemu"

# font
cask "font-jetbrains-mono"
