kind: vars
vars:
  SSH_PUBLIC_KEY: $SSH_PUBLIC_KEY # export SSH_PUBLIC_KEY="$(cat ~/.ssh/id_ed25519.pub)"
  STORAGE_POOL: ${STORAGE_POOL:-default}
  NAME: ${NAME:-dev}
  VM: ${VM:-false}
computed:
  BREW_SCRIPT: { file: brew.sh, format: base64 }
---
kind: instance
name: ${NAME}
image: images:debian/13/cloud
vm: "${VM}"
devices:
  root:
    type: disk
    pool: ${STORAGE_POOL}
    path: /
    size: 60GiB
config:
  security.nesting: "true"
  cloud-init.user-data:
    #cloud-config
    packages:
      - curl
      - git
      - stow
      - openssh-server
    users:
      - name: abiola
        shell: /bin/bash
        lock_passwd: true
        gecos: Abiola
        groups: [docker, sudo, wheel, kvm]
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
          - ${SSH_PUBLIC_KEY}
    write_files:
      - path: /tmp/brew.sh
        content: ${BREW_SCRIPT}
        permissions: "0755"
        encoding: b64
    runcmd:
      - [sudo, -u, abiola, -H, /tmp/brew.sh]
    timezone: Africa/Lagos
description: Debian instance
