[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.0

[font.bold]
style = "Medium"

[font.bold_italic]
style = "Medium Italic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[window]
decorations = "none"

