# ZSH
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="abiola"
CASE_SENSITIVE="true"

plugins=(
  git
  command-not-found
)

source $ZSH/oh-my-zsh.sh

# personal scripts
export PATH="$PATH:$HOME/bin:$HOME/dotfiles/bin"

# aliases
alias vim='nvim'
# alias flathub='flatpak install flathub'
# alias pbcopy='xclip -selection clipboard'
# alias pbpaste='xclip -selection clipboard -o'
# alias screenshot='grim -g "$(slurp)" screenshot.png'
# alias enter='toolbox enter --container'

# git commit editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# GO
export PATH="$PATH:/usr/local/go/bin:$HOME/go/bin"

# NPM
# create a ~/.npmrc with
#   prefix=/home/abiola/.npm-packages
NPM_PACKAGES="$HOME/.npm-packages"
PATH="$NPM_PACKAGES/bin:$PATH"

#fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# use python 3 by default
alias python='python3'

# gpg
export GPG_TTY=$(tty)

# bat
# alias cat='bat'
# export BAT_THEME="tomorrow-night"

